POST http://localhost:8080/user/signup
Content-Type: application/json

{
  "email": "apintogil@gmail.com",
  "password": "Barcelona2020$"
}

###

GET http://localhost:8080/user/validate?code=lTpZBwcml3mvDn4OdDHWIjARUfqYHNiArc8JRvSvpTe5eXrAIb


###

POST http://localhost:8080/user/login
Content-Type: application/json

{
  "email": "apintogil@gmail.com",
  "password": "Barcelona2020$"
}

###

POST http://covidcontact.cat:8080/user/signup
Content-Type: application/json

{
  "email": "apintogil@gmail.com",
  "password": "Barcelona2020$"
}

###

POST http://covidcontact.cat:8080/user/login
Content-Type: application/json

{
  "email": "apintogil@gmail.com",
  "password": "Barcelona2020$"
}

###

GET http://covidcontact.cat:8080/user/validated?email=apintogil@gmail.com

###

GET http://covidcontact.cat:8080/user/hello2

###
GET http://covidcontact.cat:8080/user/hello
Content-Type: application/json

{
  "username": "apintogil@gmail.com",
  "password": "Barcelona2020$"
}

###
POST http://localhost:8080/user/userinfo
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOiIxNjE3NTU3MTIwOTI3Iiwic3ViIjoiYXBpbnRvZ2lsQGdtYWlsLmNvbSJ9.Kd_6stq5Xius238k4nk0_Jo2yvOzNFlX9YuGErLec_PYkI1gsmKBJf-TLyQ4fGpRcTbYQR6XY4CNnbTWiCXiCA==
Content-Type: application/json

{
  "email": "apintogil@gmail.com",
  "username": "AlbertPG",
  "gender": "Male",
  "birth_date": 1000,
  "city": "Barcelona",
  "studies": "University",
  "occupation": "Student",
  "marriage": "Single",
  "children": 0,
  "has_been_positive": false,
  "is_vaccinated": false
}

###
POST http://localhost:8080/user/userinfo
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOiIxNjE3NTU3MTIwOTI3Iiwic3ViIjoiYXBpbnRvZ2lsQGdtYWlsLmNvbSJ9.Kd_6stq5Xius238k4nk0_Jo2yvOzNFlX9YuGErLec_PYkI1gsmKBJf-TLyQ4fGpRcTbYQR6XY4CNnbTWiCXiCA==
Content-Type: application/json

{
  "email": "albert@gmail.com",
  "username": "AlbertPG",
  "gender": "Male",
  "has_been_positive": false,
  "is_vaccinated": false
}

###
GET http://localhost:8080/user/userinfo?email=apintogil@gmail.com
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOiIxNjE3NTU3MTIwOTI3Iiwic3ViIjoiYXBpbnRvZ2lsQGdtYWlsLmNvbSJ9.Kd_6stq5Xius238k4nk0_Jo2yvOzNFlX9YuGErLec_PYkI1gsmKBJf-TLyQ4fGpRcTbYQR6XY4CNnbTWiCXiCA==

###
POST http://localhost:8080/user/device?email=apintogil@gmail.com
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOiIxNjIwMDE5ODQ3NjQwIiwic3ViIjoiYXBpbnRvZ2lsQGdtYWlsLmNvbSJ9.hRfdyd6V4MgfeI78QqlDX7puwspiv-6gwbKunH_X7TD6DFhRLDQvQw0__2wY3G4lAVygLUpskrHzBVbOSh2NSA==
Content-Type: application/json

{
  "id": "1234",
  "name": "Albert22"
}

###
POST http://localhost:8080/user/device?email=apintogil@gmail.com
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOiIxNjIwMDE5ODQ3NjQwIiwic3ViIjoiYXBpbnRvZ2lsQGdtYWlsLmNvbSJ9.hRfdyd6V4MgfeI78QqlDX7puwspiv-6gwbKunH_X7TD6DFhRLDQvQw0__2wY3G4lAVygLUpskrHzBVbOSh2NSA==
Content-Type: application/json

{
  "id": "5678",
  "name": "Albert33"
}

###
POST http://localhost:8080/user/device?email=albert.pinto@estudiantat.upc.edu
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOiIxNjIwMDE5ODQ3NjQwIiwic3ViIjoiYXBpbnRvZ2lsQGdtYWlsLmNvbSJ9.hRfdyd6V4MgfeI78QqlDX7puwspiv-6gwbKunH_X7TD6DFhRLDQvQw0__2wY3G4lAVygLUpskrHzBVbOSh2NSA==
Content-Type: application/json

{
  "id": "5678",
  "name": "Albert33"
}

###
POST http://covidcontact.cat:8080/user/userinfo
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOiIxNjE3NTU3MTIwOTI3Iiwic3ViIjoiYXBpbnRvZ2lsQGdtYWlsLmNvbSJ9.Kd_6stq5Xius238k4nk0_Jo2yvOzNFlX9YuGErLec_PYkI1gsmKBJf-TLyQ4fGpRcTbYQR6XY4CNnbTWiCXiCA==
Content-Type: application/json

{
  "email": "apintogil@gmail.com",
  "username": "AlbertPG",
  "gender": "Male",
  "birth_date": 1000,
  "city": "Barcelona",
  "studies": "University",
  "occupation": "Student",
  "marriage": "Single",
  "children": 0,
  "has_been_positive": false,
  "is_vaccinated": false
}

###
GET http://covidcontact.cat:8080/user/userinfo?email=apintogil@gmail.com
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOiIxNjE3NTU3MTIwOTI3Iiwic3ViIjoiYXBpbnRvZ2lsQGdtYWlsLmNvbSJ9.Kd_6stq5Xius238k4nk0_Jo2yvOzNFlX9YuGErLec_PYkI1gsmKBJf-TLyQ4fGpRcTbYQR6XY4CNnbTWiCXiCA==

###
POST http://covidcontact.cat:8080/user/userdevice?email=apintogil@gmail.com
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOiIxNjE3NTU3MTIwOTI3Iiwic3ViIjoiYXBpbnRvZ2lsQGdtYWlsLmNvbSJ9.Kd_6stq5Xius238k4nk0_Jo2yvOzNFlX9YuGErLec_PYkI1gsmKBJf-TLyQ4fGpRcTbYQR6XY4CNnbTWiCXiCA==
Content-Type: application/json

{
  "id": "1234",
  "name": "Albert22"
}

###
POST http://covidcontact.cat:8080/user/userdevice?email=apintogil@gmail.com
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOiIxNjE3NTU3MTIwOTI3Iiwic3ViIjoiYXBpbnRvZ2lsQGdtYWlsLmNvbSJ9.Kd_6stq5Xius238k4nk0_Jo2yvOzNFlX9YuGErLec_PYkI1gsmKBJf-TLyQ4fGpRcTbYQR6XY4CNnbTWiCXiCA==
Content-Type: application/json

{
  "id": "5678",
  "name": "Albert33"
}

###
POST http://localhost:8080/user/messagetoken
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOiIxNjIxODgwMjc1OTcxIiwic3ViIjoiYXBpbnRvZ2lsQGdtYWlsLmNvbSJ9.o-msNROMq3kNmPEbB_7RPMUfzXVmukkOQIrp_91xHMhk6joxL8giCbdLrbbXRsr9Me4yxYhR0NN1Y2OntutUxg==
Content-Type: application/json

{
  "email": "apintogil@gmail.com",
  "token": "c-1NkCbeT6OQAe0TrbfiWY:APA91bFeep5ggzQIhKRQDhOsSDVmD4Ge_7xLoBHnZBxPZm9frot5S6RMB2gkb-vnXTdEprilTR0uobSqfNTQag0QFwOnEjQxE7DA3nFbxTq36cAFnXBK5jaWpqXFxZmR5OwvimISQr2-"
}
