###
POST http://localhost:8080/contactnetwork/
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOiIxNjE5MDE2ODQ5Njk2Iiwic3ViIjoiYXBpbnRvZ2lsQGdtYWlsLmNvbSJ9.VPs_Dth4eu_SN_Wi82XdLTbRgO2m-acOUgHz6ClMAO7XNQKI0RPci8Ux6cZYvGbtNKOUn_spZbX_FzlKdQQpIQ==
Content-Type: application/json

{
  "name": "VilaTeam",
  "password": "1234",
  "owner_email": "apintogil@gmail.com",
  "owner_username": "AlbertPG#7278",
  "is_visible": false,
  "is_password_protected": true
}

###
POST http://localhost:8080/contactnetwork/
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOiIxNjE4MjE4NjcxMTM0Iiwic3ViIjoiYXBpbnRvZ2lsQGdtYWlsLmNvbSJ9.JME2eFnfjQKWnKfXmKyH_EHz-o83Zd5MFWPJ40jEhUHI8StajeqsJe7TZG7QFsgondLkD5hlh51u8HLtK70gMw==
Content-Type: application/json

{
  "name": "BarnaTeam",
  "password": "1234",
  "owner_email": "apintogil@gmail.com",
  "owner_username": "AlbertPG#6773"
}

###
GET http://localhost:8080/contactnetwork/?email=apintogil@gmail.com
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOiIxNjE4NTkyNjAzODU5Iiwic3ViIjoiYXBpbnRvZ2lsQGdtYWlsLmNvbSJ9.DJt2O2ufrdkwZvDnXzN8NudbvAj0PzPKd6amBw0hWrRPmcdyW7sUBUlhNhTMbYVU_igP0PUXKNqVEcAAN7aNKg==

###
GET http://covidcontact.cat:8080/contactnetwork/?email=apintogil@gmail.com
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOiIxNjE5MDI1NjcxMjU1Iiwic3ViIjoiYXBpbnRvZ2lsQGdtYWlsLmNvbSJ9.vbmDB_K6YWawpQPSNJi6N114CO6RM-JMexqlrhYjDk-3kzMvyBmen2F6exWp-rB8kIhhq7rTVkuWiHrqwdQXEQ==

###
PUT http://localhost:8080/contactnetwork/contactnetwork/VilaTeam%238525?isEnabled=false
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOiIxNjE5MDE2ODQ5Njk2Iiwic3ViIjoiYXBpbnRvZ2lsQGdtYWlsLmNvbSJ9.VPs_Dth4eu_SN_Wi82XdLTbRgO2m-acOUgHz6ClMAO7XNQKI0RPci8Ux6cZYvGbtNKOUn_spZbX_FzlKdQQpIQ==

###
PUT http://covidcontact.cat:8080/contactnetwork/VilaTeam%231850?isEnabled=false
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOiIxNjE5MDE2ODQ5Njk2Iiwic3ViIjoiYXBpbnRvZ2lsQGdtYWlsLmNvbSJ9.VPs_Dth4eu_SN_Wi82XdLTbRgO2m-acOUgHz6ClMAO7XNQKI0RPci8Ux6cZYvGbtNKOUn_spZbX_FzlKdQQpIQ==

###
PUT http://localhost:8080/contactnetwork/VilaTeam%231850/generateAccessCode
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOiIxNjE5NzkzOTQ2ODAwIiwic3ViIjoiYXBpbnRvZ2lsQGdtYWlsLmNvbSJ9.tHaKn57mLnlDVJtTdo9pC7x2UdonJMe9gAnBw81bVIlRIO693zVYzrEy89kypvg5YEPDxf9DVT2FdPItCpC5UQ==

###
GET http://localhost:8080/contactnetwork/accessCode?code=222857
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOiIxNjIwMDE5ODQ3NjQwIiwic3ViIjoiYXBpbnRvZ2lsQGdtYWlsLmNvbSJ9.hRfdyd6V4MgfeI78QqlDX7puwspiv-6gwbKunH_X7TD6DFhRLDQvQw0__2wY3G4lAVygLUpskrHzBVbOSh2NSA==

###
PUT http://localhost:8080/contactnetwork/Fibers%231012/join?email=apintogil@gmail.com
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOiIxNjIwMDE5ODQ3NjQwIiwic3ViIjoiYXBpbnRvZ2lsQGdtYWlsLmNvbSJ9.hRfdyd6V4MgfeI78QqlDX7puwspiv-6gwbKunH_X7TD6DFhRLDQvQw0__2wY3G4lAVygLUpskrHzBVbOSh2NSA==


###
POST http://localhost:8080/contactnetwork/
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOiIxNjIxODgwMjc1OTcxIiwic3ViIjoiYXBpbnRvZ2lsQGdtYWlsLmNvbSJ9.o-msNROMq3kNmPEbB_7RPMUfzXVmukkOQIrp_91xHMhk6joxL8giCbdLrbbXRsr9Me4yxYhR0NN1Y2OntutUxg==
Content-Type: application/json

{
  "name": "Joves",
  "password": "1234",
  "owner_email": "apintogil@gmail.com",
  "owner_username": "AlbertPG#7721",
  "is_visible": false,
  "is_password_protected": true
}
